on: [push]

jobs:
  upload-sbom:
    runs-on: ubuntu-latest
    - name: Generate Python SBOM
      uses: CycloneDX/gh-python-generate-sbom@v2
      with:
        input: ./requirements.txt
        output: ./bom.json
        format: json
